# ================================================================
# CONFIGURATION SPRING BOOT - LOT 5 : MEDILINK LOT5
# ================================================================

spring.application.name=medilink_lot5

# ================================================================
# CONFIGURATION BASE DE DONNEES POSTGRESQL (Supabase)
# ================================================================
spring.datasource.url=jdbc:postgresql://db.kqoncuduyigktlvgnlse.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ROIDESROI10
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

# ================================================================
# HIBERNATE SPATIAL - CONFIGURATION
# ================================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ================================================================
# CONFIGURATION SERVEUR - LOT 2 (Patient/RDV)
# ================================================================
server.port=8085

# ================================================================
# CONFIGURATION LOGGING
# ================================================================
logging.level.root=INFO
#ligne manquante
logging.level.org.hibernate.SQL=DEBUG



